### ISSUE TITLE
installer doesn't check for pre-requisites

### ISSUE THREAD

**Issue by slchorne** [dnsviz/dnsviz#10]
yes, i know they are documented in the README, but the installer should croak if the pre-requisites aren't met.

**Comment by cdeccio** [comment]
Because dnspython is a run-time dependency, it's possible and allowable that the package is built and packaged on a system that doesn't have it installed, even if it is required at run-time.  I've added a check to the bin/dnsviz script rather than to the build/install, so it can be built and installed without it.

Note that the other dependencies (M2Crypto and pygraphviz) aren't hard requirements, so the check for those dependencies is only invoked when their functionality is needed.
