### ISSUE TITLE
Possible AssertionError

### ISSUE THREAD

**Issue by mdavids** [dnsviz/dnsviz#42]
Reproduce with:

_sidn._dnssec-valcheck-20181105.Z-1555758588.caravanmover-professionals.nl.

Or see:

http://dnsviz.net/d/_sidn._dnssec-valcheck-20181105.z-1555758588.caravanmover-professionals.nl/W-FlRA/dnssec/

Commandline version gives;

/usr/local/Cellar/dnsviz/0.6.7/libexec/lib/python2.7/site-packages/dnsviz/response.py",
                line 1054, in __init__
assert rrset.name not in self.rrsets

**Comment by Habbie** [comment]
https://gist.github.com/Habbie/7e12b9d092a212ba299ed953d3cfabeb has 3 `dnsviz probe` JSON blobs for a related domain that, when fed to `dnsviz print`, cause different (assertion) aborts.

**Comment by cdeccio** [comment]
I saw some of these errors yesterday.  The problem is that the response is returning `NSEC` records from different classes (i.e., other than `IN`).  The DNSViz code was initially pulling class-agnostic, assuming that all RRs returned are type `IN`.  I'm working on a fix that filters out non-`IN` RRs and displays those in a different place, rather than making them part of the `NSEC` records used for negative responses.

**Comment by Habbie** [comment]
Yes, I had the same impression. I spent some time poking at the DNSViz code to make it class aware but it looked like a daunting task. Just putting them aside does make more sense!

**Comment by cdeccio** [comment]
Yes, daunting because of the spaghetti code :) But I think 5ccbd8e fixes this.

**Comment by Habbie** [comment]
https://gist.github.com/Habbie/e4d2e1882de709383afff0387237c183 has 3 captures of `dnsviz probe mikkeller.nl` that `dnsviz print` chokes on for me, with 5ccbd8e (unless I did something dumb in my Python devenv).

**Comment by cdeccio** [comment]
What is the error?  Is it the same assertion error that @mdavids was seeing in the original issue request?  Did it always exist, or is it just since 5ccbd8e?  I'm seeing issues with `mikkeller.nl`, but not the same ones from the current issue (and I think they already were a problem, just not documented in an issue).

**Comment by Habbie** [comment]
No, different error - I saw this before, I just assumed it was the same class issue:

```
  File "/Users/peter/projects/powerdns/dnsviz/dnsviz/analysis/offline.py", line 381, in _serialize_response_component_simple
    status = Status.rrset_status_mapping[self.response_component_status[info]]
KeyError: <RRsetInfo: "RRset for mikkeller.nl/A">
```

When I inspected this before your fix, I would find that such an RRset was in fact there, but it did not match the dict lookup - presumably because of the different class.

**Comment by cdeccio** [comment]
Okay, that's what I'm getting.  I can reproduce it, but haven't narrowed it down yet.  I'm going to create a new issue to track it.

**Comment by Habbie** [comment]
ok!
