### ISSUE TITLE
Not responding to queries over UDP

### ISSUE THREAD

**Issue by gemal** [dnsviz/dnsviz#57]
I seem to have a problem with:
https://dnsviz.net/d/book.dinnerbooking.com/dnssec/

dinnerbooking.com zone: The server(s) were not responsive to queries over UDP. (2001:978:2:6f::1f:53)

I checked manually and it seems that the server response normally to UDP. I wonder why it says this?

The same here:
https://dnsviz.net/d/dinnerbooking.com/dnssec/

**Comment by gemal** [comment]
and everything seems ok here:
https://zonemaster.iis.se/?resultid=9383da8ac0d861d3

**Comment by cdeccio** [comment]
In short, it's hard to tell.  Zonemaster and DNSViz issue queries from different vantage points, and there are many factors for which one would have issues and the other not.  In general, it's best to issue these types of questions using the "contact" link at https://dnsviz.net/contact/ since it's not really an issue with the DNSViz code, but a question about output from the deployment of the code at https://dnsviz.net/.
