### ISSUE TITLE
com/DS: No response was received from the server over UDP (tried 12 times).

### ISSUE THREAD

**Issue by danielnaaman** [dnsviz/dnsviz#73]
Hey, I received the following error while inspecting my domain. I'm having a hard time figuring out if the issue is with the root servers, the site or my settings.

The issue:
`com/DS: No response was received from the server over UDP (tried 12 times). (192.228.79.201, 193.0.14.129, 199.9.14.201, UDP_-_NOEDNS_)`

[The test in question](https://dnsviz.net/d/danielnaaman.com/YCvHBQ/dnssec/)

Sincerely,
Daniel Naaman

**Comment by cdeccio** [comment]
Hi Daniel, I'm honestly don't know if the errors experienced were because of temporary issues in connectivity between the server and the intended targets (more likely) or just that the servers were unresponsive when you ran the test (less likely), but as far as the code is concerned, it is doing its job.  Thanks.
