### ISSUE TITLE
bad NSEC delegation to insecure not detected

### ISSUE THREAD

**Issue by vcunat** [dnsviz/dnsviz#78]
Example: https://dnsviz.net/d/kupaliska.netmarketer.sk/YJPGcA/dnssec/

The NSEC that's meant to prove non-existence of DS for the delegation actually proves NXDOMAIN for the delegation (the name is covered by the NSEC range, not matched).   Dnsviz certainly should detect such errors, as correct validators must not pass through such a delegation.

**Comment by cdeccio** [comment]
Ack.  Thanks, sorry for the delayed response.  I'll have a look soon.

**Comment by cdeccio** [comment]
Okay, so I think what I'm seeing is that the response given by the server is a "wildcard No Data" response.   That is because:
 - the rcode is NOERROR
 - one NSEC record covers the queried name itself
 - the other NSEC record corresponds to a wildcard record
 - that NSEC record with the wildcard as the owner name doesn't cover the queried name
 - that NSEC record with the wildcard as the owner name doesn't include the DS type, but it also doesn't include the NS type--I think *that* is the issue.
I'll check the code and see if I'm getting the wildcard NSEC record if an NSEC record for the queried name itself doesn't exist.

**Comment by cdeccio** [comment]
I've committed some changes in the `check_wildcard_delegation` branch for testing.

```
$ dnsviz probe kupaliska.netmarketer.sk | dnsviz grok -lerror
Analyzing kupaliska.netmarketer.sk
Analyzing netmarketer.sk
Analyzing sk
Analyzing .
{
    "kupaliska.netmarketer.sk.": {
        "queries": {
            "kupaliska.netmarketer.sk./IN/DS": {
                "nodata": [
                    {
                        "id": "kupaliska.netmarketer.sk./IN/DS",
                        "proof": [
                            {
                                "id": "NSEC",
                                "status": "INVALID",
                                "errors": [
                                    {
                                        "description": "The NS bit was not set in the bitmap of the NSEC RR corresponding to the delegated name (*.netmarketer.sk).",
                                        "code": "REFERRAL_WITHOUT_NS"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        },
        "delegation": {
            "insecurity_proof": [
                {
                    "id": "NSEC",
                    "status": "INVALID",
                    "errors": [
                        {
                            "description": "The NS bit was not set in the bitmap of the NSEC RR corresponding to the delegated name (*.netmarketer.sk).",
                            "code": "REFERRAL_WITHOUT_NS"
                        }
                    ]
                }
            ],
            "status": "BOGUS"
        }
    }
}
```
Comments?

**Comment by vcunat** [comment]
I can't recall that wildcard delegations have ever been well-defined; I certainly wouldn't advise using them. https://datatracker.ietf.org/doc/html/rfc4592#section-4.2

**Comment by cdeccio** [comment]
Agreed on both points.  And actually I don't think it's even a wildcard delegation (because there is no NS record at the wildcard).  It _is_, however, a wildcard no data response, which explains why the response code is NOERROR.  As far as the parent is concerned, it is simply a non-delegation.  The behavior is very similar to an NXDOMAIN at the parent.

**Comment by vcunat** [comment]
Oh, right, also in the NSEC bitmap.  It didn't seem that I thought so months ago either.

Hmm, so this could be result of loading both zones on those servers without adding a zone cut?

**Comment by cdeccio** [comment]
Yes!  I believe this is exactly that.  The difference between this and getting an NXDOMAIN response in the same situation (parent is authoritative for child) is that this particular zone has a wildcard.  In fact, I'm revising my code now such that the error actually indicates that it is a non-delegation where the parent is authoritative for the child.
