### ISSUE TITLE
Treatment of SHA-1 keys is wrong

### ISSUE THREAD

**Issue by paulehoffman** [dnsviz/dnsviz#79]
For DNSSEC keys that use digest algorithm 1, DNSviz reports:
`$domain/DS (alg 8, id 35230): DNSSEC specification prohibits signing with DS records that use digest algorithm 1 (SHA-1).`
That is both wrong and inflammatory. RFC 8624 says that implementations MUST NOT create such DS records, but it **absolutely does not** prohibit such records in zones. DNSviz saying that the specification prohibits this misleads the reader of the output.

**Comment by cdeccio** [comment]
Thanks for the interest.  A few things:

1. You're correct that RFC 8624 stops short of saying that existence of DS records using SHA1 is prohibited.  That is why it's a warning at this point and not an error.  But I don't believe that allowing them is consistent with the spirit of the RFC.  According to the table in Section 3.3, digest alg 1 (SHA-1) MUST NOT be used with "DNSSEC Delegation".  That doesn't seem very ambiguous.  The only reason that "validators MUST implement validation" is that "SHA-1 is still widely used for Delegation Signer (DS) records".  Note that that is not a sanction, merely an observation, so validation of existing zones doesn't go dark.
2. Even if existing records were allowed (and only new ones were not), there is really no way in DNSViz to tell a user that it's wrong _before_ it's put it in--at least not in the way that it is most widely used.  So how it would it be done _effectively_ otherwise?  Part of the point of the diagnostic tool is to let users know _now_ of something that might be a problem in the future; hence the warning.  What percentage of DNS operators do you think take the time to go read new RFCs?  See also the original ticket #69.
3. I'm also not sure how it is inflammatory.  In fact, I find that comment inflammatory! 😄 Are you suggesting something less direct?

**Comment by paulehoffman** [comment]
1. With all due respect, the RFC says exactly what it means. There was lots of long discussions before the wording in the RFC was finalized, so you saying what you think "the spirit" of the RFC shows disrespect for those of us who worked hard on the wording. Further, the table in Section 3.3 says no such thing. The RFC is about implementations, not about use, so you saying "MUST NOT be used" directly contradicts the RFC itself.

2. I don't understand what you are indicating here. It is not DNSviz's place to try to guess intention of operators, only report on what is seen.

3. It is inflammatory because you say "prohibits" when it does not, so someone reading the text can think that the zone is incorrect when it is not. (I'm saying this because that exact misinterpretation happened and that's what alerted me to these messages.) 

I'm not suggesting "something less direct", I'm directly asking for the text to be correct. If you want a warning, you can say that RFC 8462 says that implementations should not have created this record, but they did. You could even say that using a different hash algorithm is considered better.

**Comment by cdeccio** [comment]
Thanks for the feedback and for the discussion.  I'll give it some thought, but I don't foresee it being changed in the near future.

**Comment by cdeccio** [comment]
Okay, there was some miscommunication, and I understand now what I didn't understand before.  Please take a peek at #145 and see if that's better.

**Comment by cdeccio** [comment]
Fixed with #145 .
